pi_site/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("list/", views.PostListView.as_view(), name="post_list"),
    path("detail/<slug:slug>/", views.PostDetailView.as_view(), name="post_detail"),
]

pi_site/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
]

pi_site/blog/models.py
from django.db import models
from django.urls import reverse

from config import core_models


class PublishedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class DraftPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.DRAFT)


class DeletedPostManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.DELETED)


class Post(core_models.CommonModel):
    title = models.CharField(
        verbose_name="заголовок",
        max_length=256,
    )

    sub_title = models.CharField(
        verbose_name="подзаголовок",
        max_length=256,
    )

    slug = models.SlugField(
        verbose_name="Slug",
    )

    text = models.TextField(
        verbose_name="текст",
    )

    description = models.TextField(
        verbose_name="описание",
    )

    conclusion = models.TextField(
        verbose_name="заключение",
    )

    class Status(models.TextChoices):
        DRAFT = "DR", "Черновик"
        DELETED = "Dl", "Удалено"
        PUBLISHED = "PB", "Опубликовано"

    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT,
        verbose_name="статус",
    )

    objects = models.Manager()
    published = PublishedPostManager()
    draft = DraftPostManager()
    deleted = DeletedPostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "пост"
        verbose_name_plural = "посты"

pi_site/blog/views.py
from django.views import generic

from . import models


class PostListView(generic.ListView):
    model = models.Post
    queryset = models.Post.published.all()
    template_name = "blog/post_list.html"


class PostDetailView(generic.DetailView):
    model = models.Post
    queryset = models.Post.published.all()
    template_name = "blog/post_detail.html"

pi_site/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>{{ object.title }}</title>
</head>
<body>
<h1>{{ object.title }}</h1>
<h3>{{ object.sub_title }}</h3>
<h3>{{ object.description }}</h3>
<hr>
<p>{{ object.text }}</p>
<hr>
{{ object.conclusion }}

<p>Спасибо за прочтение! <a href="{% url "blog:post_list" %}">Список всех постов.</a></p>
</body>
</html>

pi_site/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>Главная страница</title>
</head>
<body>
	<h1>Технологии внедрения программного обеспечения</h1>
	<h2>Посты</h2>
	<hr>
	{% for post in object_list %}
		<a href="{% url "blog:post_detail" slug=post.slug %}"><h3>{{ post.title }}</h3></a>
		<h4>{{ post.sub_title }}</h4>
		<div>{{ post.description }}</div>
		<hr>
	{% endfor %}
</body>
</html>